### ISSUE TITLE
Core Algorithms - version 1.0, 2.0 and 3.0

### ISSUE THREAD

**Issue by Devwarlt** [Devwarlt/pstk-core#1]
# Core Algorithms
**Motivation:** due some several technical issues found along PServers over the years related to lag, rubberbading, network and other issues kinda related to themselves, they were still a challenge for PServer developers to solve and most of them given up along possible patches for this scenario.

Therefore, after some weeks studying about possible patch, I decided to investigate what is the relationship between each other (lag, rubberbanding, network issues occurrences) and just found an algorithm whose integrates all of them, see [**`FLLogicTicker`**][ref-1] for more details. Summarizing, this algorithm is responsible to render and simulate the game time every **200** milliseconds whose represents **1** tick of [**`RealmTime`**][ref-2].

So, based on this situation **Core Algorithms** (***CA***) come to split this overwhelming task and build an organized way to manage internal methods that require intense / massive processing over ticks of time based on system environment specs.

---

## How CA would impact in game performance for NR-Core servers?
> CA is designed to manage not exclusively time and tick operations, but critical threads that require such attention by processor cores provided by system environment. CA use a powerful feature from .NET framework available since C# 4.0 which is **PFX** (Performance Framework) whose contains definitions for **parallel programming** and **concurrency** scenarios, see [**`Joe Albahari's article`**][ref-3] about this topic.

---

### `Version 1.0`
Replacement for time simulation to system environment tick core (not needed to simulate a time since system already does that).

### `Version 2.0`
Multithreading based-off on Joe Albahari's article to split threads that require to not being synchronous, but asynchronous instead (currently main issue found along debug diagnoses made).

### `Version 3.0`
Improvements along multithreading procedures on CA and replacement of **Core Task** to **Core Thread** due thread-unsafe issues, see this [**`article`**][ref-4] for more details.

---

## TO-DO List
- [x] deprecate **`RealmTime`** struct
- [x] brings **`RealmTime`** replacement
- [x] brings multithreading and processor core implementations to split inner threads
- [x] brings **Core Thread** and **World Tick** operations

[ref-1]: https://github.com/cp-nilly/NR-CORE/blob/070977917893a5fbb6fe9598e5d63ff8c62fa10c/wServer/realm/FLLogicTicker.cs
[ref-2]: https://github.com/cp-nilly/NR-CORE/blob/070977917893a5fbb6fe9598e5d63ff8c62fa10c/wServer/realm/RealmManager.cs#L19-L25
[ref-3]: http://www.albahari.com/threading/
[ref-4]: https://www.c-sharpcorner.com/UploadFile/1c8574/thread-safety369/
